### ISSUE TITLE
Had an issue importing rdkit

### ISSUE THREAD

**Issue by Dfvandenberg** [DanilKrivonos/BioCAT#2]
Hi Danil,

There is a small spelling mistake in the example code:
biocat -smiles '[H][C@@]1(CCC(O)=O)NC(=O)CC(CCCCCCCCCCC)OC(=O)[C@]([H])(CC(C)C)NC(=O)[C@@]([H])(CC(C)C)NC(=O)[C@]([H])(CC(O)=O)NC(=O)[C@@]([H])(NC(=O)[C@@]([H])(CC(C)C)NC(=O)[C@]([H])(CC(C)C)NC1=O)C(C)C' -name 'surfactin' -genome example/Surfactine/GCF_000015785.2_ASM1578v2_genomic.fna -out surfactin_results 

The path to the GCF_000015785.2_ASM1578v2_genomic.fna should be with Surfactin instead of Surfactine in the path name to make it work.
Another thing I ran into was that the rdkit module wasn't found when using biocat, which was solved when using python3 and then the path to the biocat itself.

In my case it looked like this:
python3 /home/daan/.local/bin/biocat -smiles '[H][C@@]1(CCC(O)=O)NC(=O)CC(CCCCCCCCCCC)OC(=O)[C@]([H])(CC(C)C)NC(=O)[C@@]([H])(CC(C)C)NC(=O)[C@]([H])(CC(O)=O)NC(=O)[C@@]([H])(NC(=O)[C@@]([H])(CC(C)C)NC(=O)[C@]([H])(CC(C)C)NC1=O)C(C)C' -name 'surfactin' -genome example/Surfactine/GCF_000015785.2_ASM1578v2_genomic.fna -out surfactin_results

I do not know what caused it, but it wasn't able to find rdkit eventhough I was able to import it manually within python and python3 in the command line.

With kind regards,
Daan

**Comment by DNKonanov** [comment]
Hi Daan,

Thank you for your feedback! 

I have fixed the spelling mistake you mentioned and a couple of others.

I did not have the problem with RDKit you have described. I see that your biocat is located in /home/daan/.local/bin/biocat. It seems that  `pip` you use does not belong to the created conda environment. Please make sure that the conda environment is activated and check which `pip` you are using with `which pip` command.

**Comment by DNKonanov** [comment]
P.S. I think there is another option for you to fix the problem - just change the first line in the /home/daan/.local/bin/biocat file to the path to the python interpreter you need, for example
`#!/home/daan/anaconda3/envs/biocat_env/bin/python3`

definitely, it is not the best solution :) in my opinion, it is better to figure out what's wrong with your `pip` in order to avoid similar problems in the future

**Comment by Dfvandenberg** [comment]
Hi,

Sorry for the late reply!
I think there was something wrong with my pip indeed. Thanks for the reply!
